config/routes.rb
Lcware::Application.routes.draw do
  resources :projects

  root to: 'application#home'

  match '/home',            to: 'application#home'
  match '/resume',          to: 'application#resumay'
  match '/myblog',          to: 'application#myblog'
  match '/get_word_resume', to: 'application#get_word_resume'
  match '/bio',             to: 'application#bio'
  match '/fpg',             to: 'application#fpg'

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :language, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def home
    render 'layouts/home'
  end

  def bio
    render 'layouts/bio'
  end

  def resumay
    render 'layouts/resumay'
  end

  def myblog
    render 'layouts/myblog'
  end

  def get_word_resume
    send_file 'public/resume_LChastain.doc', :type=>'application/msword'
  end

  # Full Page Graphic (from a click on an element that has a large popup balloon)
  def fpg
    @grafik = params[:grafik]
    render 'layouts/fpg'
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.orig.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/_header.html.erb
<style type="text/css">
</style>

<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= image_tag 'lcware.png', :alt => "ElseWare", :id => "logo"  %>
      <nav>
        <ul class="nav pull-right">
            <!--
            <li>< %= link_to "Dashboard",  projects_path %></li>
            <li style="position: relative; left: -14px;" class="dropdown">
              <a href="#"  class="dropdown-toggle" data-toggle="dropdown" >
                  <b class="caret" style="font-size: 0;"></b>
              </a>
              <!-- Dashboard -->
              <!--suppress HtmlUnknownAttribute -->
              <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu">
                  <li><%= link_to "games",      projects_path %>  </li>
                  <li><%= link_to "users",      projects_path %>
                  <li><%= link_to "sessions",   projects_path %>
                  <li><%= link_to "states",    projects_path %>
                  <li class="pull-right"><%= link_to "installed",    projects_path %>
                  <li class="pull-right"><%= link_to "homeless",    projects_path %>
              </ul>

          <li><%= link_to "Home",       'home' %></li>
          <li><%= link_to "Resume",     resume_path %></li>
          <li><%= link_to "Bio",        'bio' %></li>
          <li><%= link_to "My Blog",    myblog_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>LC | <%= yield(:title) %></title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <% unless @suppress_prototype %>
        <%= javascript_include_tag  "prototype", "balloon.config", "balloon", "box" %>
    <% end %>

    <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/header" %>

<%= yield %>

</body>
</html>

app/views/layouts/bio.html.erb
<% provide(:title, 'Bio Page') %>

<h1 style="margin-bottom: 0; padding-bottom: 0">
Personal info for Lee Chastain
</h1>
<hr style="width:100%; height: 4px; color:#000000; background-color: black; margin-top: 5px;" />

<div style="float: left">
    <h3>My Photo</h3>
    <%= image_tag('img_0077.jpg', :height => '60%', :width => '60%') %>
</div>

<div style="float: right">
    <h3>My Gravatar</h3>
    <%= image_tag('underdog.gif', :height => '40%', :width => '40%') %>
</div>

<div style="clear: both"></div>

<div style="margin-top: 20px; font-size: 18px; line-height: 24px;">
    Born in Marlin, TX but my parents had an adventurous spirit so two years later we all
    moved to Alaska - too many highlights there to mention on this page but we did make our own homestead
    and my childhood was memorable.  Fast-forward to senior year at Buena High School in Sierra Vista, AZ and
    then on to 2.5 years at the University of Arizona in Tucson (studying Electronics, Journalism
    and Russian) before losing focus and going into a period of trying other things such as clerk-typist,
    stock clerk, lifeguard, security guard, locksmith.  Eventually joined the Navy and got some solid
    hands-on training in electronics, and the career was 'on'.  After the Navy I still wanted to get a degree
    but this time I had to pursue it along with working and providing for my family so it was a slow, painful
    process and in fact spanned a couple more universities (University of California at Irvine & West Coast
    University) and several more years before finally achieving the Bachelor of Science in Computer
    Science and Mathematics from California State University - Long Beach, while working at TRW.
    While my cumulative GPA had suffered from all the false
    starts, the average of the later upper-level course work done in residence at CSULB was much better (3.5).
    After earning the bachelor's degree, moved back to Arizona and continued to work as a computer scientist
    by day and as a student by night, to earn a master's degree in Computer Information Systems.
    Eventually made it back to Texas, in 2008.
</div>

<!-- Make some room at the bottom.  -->
<div style="height: 60px;"></div>

app/views/layouts/fpg.html.erb
<% provide(:title, 'Full Page Graphic') %>

<%= image_tag(@grafik, :onclick => "history.back();return false;") %>

app/views/layouts/home.html.erb
<% provide(:title, 'ElseW@re Home') %>

<h1 style="margin-bottom: 0; padding-bottom: 0">
ElseW@re - Lee Chastain's personal web site
</h1>
<span style="margin-left: 320px;">
    (for shameless self promotion)
</span>

<h4 style="margin-top: 40px;">
    For now - the
    <a href="/resume">
        resume
    </a>
    page is complete and of the most interest.
</h4>
<h5 style="margin-left: 20px;">
    When you go there, be sure to mouse over the text in each section; there are several<br>
    'easter eggs' throughout.  For example, when you find the US Navy Seal, see what<br>
    happens when you click there.  Another click (afterwards) is also useful.
</h5>

<h4 style="margin-top: 30px;">
    For later -
</h4>
<h5 style="margin-left: 20px;">
    I am currently working on adding code examples and apps from various past <br>
    programming projects, but this RoR site is already one example in itself.<br>
    Till then - here are some screen shots from some of those apps:
</h5>

<div style="height: 30px;"></div>

<%= image_tag('ukodus_x.png') %>
<%= image_tag('colt_radio.png') %>
<%= image_tag('perslog_5.png') %>
<%= image_tag('acro.png') %>
<%= image_tag('stratmap.jpg') %>

app/views/layouts/myblog.html.erb
<% provide(:title, 'My Blog') %>

<p style="text-align:center;">
    <span style="font-family:Cursive, serif;font-size:48px;font-style:normal;font-weight:normal;
            text-decoration:none;text-transform:none;color:#000000;">
        My Blog
    </span>
</p>

<br>
<h3 style="text-align: center">
    <span style="width:100%">No Comment.</span>
</h3>
<%= image_tag "smylee.jpg", :alt => ":)", :id => "smylee",
    :style => "display: block; margin-left: auto; margin-right: auto; height: 100px; width: 100px;"
%>

app/views/layouts/resumay.html.erb
<% provide(:title, 'Resume') %>

<!-- Initialize the popup balloon -->
<script type="text/javascript">
    // Initialization of the popup tooltip container - white balloon with default configuration.
    var balloon = new Balloon();
</script>

<!-- Download button, Name, Link to GitHub -->
<p style="text-align:center;">
    <span style="font-family:Cursive, serif;font-size:36px;font-style:normal;font-weight:bold;
            text-decoration:none;text-transform:none;color:#0033CC; margin-left: -160px">
        Donald L. Chastain
    </span>
    <br>
</p>
<hr style="width:100%; height: 4px; color:#000000; background-color: black" />
<h4>
    New Objective
</h4>
Flying under the radar
<br>
<br>
<br>

<!-- Make some room at the bottom.  -->
<div style="height: 100px;"></div>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :language %><br />
    <%= f.text_field :language %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<% provide(:title, 'Projects') %>
<h1>Listing projects</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Language</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= project.name %></td>
    <td><%= project.language %></td>
    <td><%= link_to 'Show', project %></td>
    <td><%= link_to 'Edit', edit_project_path(project) %></td>
    <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @project.name %>
</p>

<p>
  <b>Language:</b>
  <%= @project.language %>
</p>


<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>